### ISSUE TITLE
status line does not appear

### ISSUE THREAD

**Issue by sudhih** [nvimdev/modeline.nvim#2]
Hello @glepnir,
I've installed the plugin using `packer`. I've added `require('whiskyline').setup()` somewhere in my `init.lua` file(I assume this is the way to initialize & start it), but i only see default status line, not the one in the `README.md` of this repo.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/11577622/226270326-af0063e1-0469-4d87-9ee8-bdb31de53809.png">

Could you please help. I added couple of `print` statements to see whether `setup()` actually gets called or not. I see its getting called but no change in status line. 

Thanks in advance,

--
Sudhir.

**Comment by glepnir** [comment]
after `PackerCompile` it still not work ?

**Comment by sudhih** [comment]
Yes, i just tried running `:PackerCompile` without any argument. Restarted the `nvim` still don't see it...

BTW, thanks for quick reply. Much appreaciated.

--
Sudhir.

**Comment by glepnir** [comment]
gitsign use my fork ?

**Comment by sudhih** [comment]
i read that in `README.md` & i understood, one has to use/checkout `patch_2` branch? but i don't see any other branch other than `main`. is my understanding right?

**Comment by sudhih** [comment]
ok, you are asking to use `patch_2` branch of `glepnir/gitsigns` . I've not installed `gitsigns` yet. is that a requirement?

**Comment by glepnir** [comment]
try it .

**Comment by sudhih** [comment]
hello @glepnir,
i tried below steps, but still don't see expected status line

1. installed `glepnir/gitsigns.nvim`
<img width="960" alt="image" src="https://user-images.githubusercontent.com/11577622/226287685-fa8a9a96-3a89-4a7d-8ce5-7eb3e2561a5d.png">
2. explicitly checkedout `patch_2 `branch from the installed location

<img width="507" alt="image" src="https://user-images.githubusercontent.com/11577622/226287412-c0c220c7-f821-442b-abbb-8b57a68c8dba.png">
4. added `require('gitsigns').setup()` line in my `init.lua` file. Still don't see.  The 👆 is showing status line is still default.

**Comment by glepnir** [comment]
works fine on my local 

![image](https://user-images.githubusercontent.com/41671631/226304991-07b72ae0-60d2-4aa5-88f0-a32f1d8357ca.png)

**Comment by sudhih** [comment]
Hello @glepnir 
is there anything I should try as a debug step, kindly advice. Some how it still doesn't appear in my setup. I'll try again sometime this week.

**Comment by sudhih** [comment]
hello @glepnir 
I was using `nvim v0.8.2` current stable version. 
I upgraded to `nighly`, now it works as expected.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/11577622/229524706-3ffdb6c4-b623-4fe7-a868-ef4826fca027.png">
